version: "3.9"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - apidb:/var/lib/mysql
    healthcheck:
        test: "/usr/bin/mysql --user=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

  api:
    image: bookstore-api
    container_name: api
    build:
      dockerfile: build/api/Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      ART_ENV: docker
    depends_on:
      mysql:
        condition: service_healthy

volumes:
    apidb: