
@url=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlzcyI6ImJvb2tzdG9yZSIsImV4cCI6MTcyODIwMjg1NiwiaWF0IjoxNzI4MTE2NDU2LCJqdGkiOiIzMGI5NjdjOC0zNDA5LTRkZTMtOTViZi0wY2I1MzYzOWYyZTEifQ.nD9Fze3zWV_JenGoDmo0aQ4_mbI_faHrlwlw8Iwwf4k
###Create book

POST {{url}}/v1/admin/books HTTP/1.1
Authorization: Bearer {{token}}

{
    "id": "b63240b9-f98b-4c12-8197-78f10ca7dc26",
    "title": "Test",
    "author": "J.D. Salinger",
    "publisher": "Oreally",
    "isbn": "9780316769100",
    "year": 2024,
    "edition": 1,
    "rating": 7
}

###List books
GET {{url}}/v1/books HTTP/1.1
Authorization: Bearer {{token}}

###Get book
GET {{url}}/v1/books/550e8400-e29b-41d4-a716-446655440010 HTTP/1.1
Authorization: Bearer {{token}}