
@url = http://localhost:8080
###Create book

POST {{url}}/v1/books HTTP/1.1

{
    "id": "550e8400-e29b-41d4-a716-446655440010",
    "title": "Golang",
    "author": "J.D. Salinger",
    "publisher": "Oreally",
    "isbn": "9780316769998",
    "year": 2024,
    "edition": 1,
    "rating": 7
}

###List books
GET {{url}}/v1/books HTTP/1.1

###Get book
GET {{url}}/v1/books/1 HTTP/1.1