
@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlzcyI6ImJvb2tzdG9yZSIsImV4cCI6MTcyODI3NzM4MSwiaWF0IjoxNzI4MTkwOTgxLCJqdGkiOiI2OGEzNDljZS0xZjU5LTQxNzMtYmI1OS04MTg2OThlOTQzZTMifQ.ZEDhq_7rLdR9XKufqad4Ksbeh79jiTh-0XOG4Oums5k

###
POST {{url}}/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin@bookstore.com",
    "password": "admin"
}

###
POST {{url}}/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "vishal@gmail.com",
    "password": "vishal"
}

###
POST {{url}}/v1/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}