bases:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

commonLabels:
  env: staging

namespace: staging

images:
  - name: bookstore
    newName: docker.io/vishalanarase/bookstore
    newTag: latest
