apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
    env: dev
  name: bookstore-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server
    env: dev
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
    env: dev
  name: bookstore
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      env: dev
  template:
    metadata:
      labels:
        app: web-server
        env: dev
    spec:
      containers:
      - image: docker.io/vishalanarase/bookstore:latest
        name: application
