name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: mysql:latest
    #     env:
    #       MYSQL_ALLOW_EMPTY_PASSWORD: yes
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install soda cli
        run: go install github.com/gobuffalo/pop/soda@v4.13.1
      - name: Soda go-version
        run: soda --verdion

      - name: Build
        run: go build -v ./...

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: "test"
          mysql password: "test"
          mysql root password: ""
          mysql database: "bookstore_api_test"

      - name: Run testmigrations
        run: make testmigrations

      - name: Test
        run: go test -v ./...
