name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          #MYSQL_DATABASE: bookstore_api_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=2s --health-timeout=20s --health-retries=10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install soda cli
        run: go get github.com/gobuffalo/pop/v6/soda@latest && go install github.com/gobuffalo/pop/v6/soda@latest
      - name: Soda cli version
        run: soda --version

      - name: Go Build
        run: go build -v ./...

      - name: Run testsetup
        run: |
          set +e
          make testsetup
          exitcode=$?
          if [[ $exitcode -eq 2 ]]; then
            exit 0
          else
            exit $exitcode
          fi

      - name: Go Test
        run: go test -v ./...
        env:
          API_ENV: "test"
          DATABASE_USERNAME: "root"
          DATABASE_PASSWORD: ""
          DATABASE_NAME: "bookstore_api_test"
          DATABASE_PORT: 3306
